openapi: 3.0.3
info:
  title: Provider API
  version: 1.0.0

paths:
  /providers:
    post:
      summary: Create multiple providers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                providers:
                  type: array
                  items:
                    $ref: '#/components/schemas/Provider'
              required:
                - providers
      responses:
        '201':
          description: Providers created successfully
        '400':
          description: Invalid input

components:
  schemas:
    Provider:
      type: object
      additionalProperties: false
      properties:
        providerName:
          type: string
          minLength: 1
        providerType:
          type: array
          items:
            type: string
          minItems: 1
          uniqueItems: true
        constitutionalStatus:
          type: string
        indemnityReceivedDate:
          type: string
          format: date
          description: Date in ISO 8601 format (YYYY-MM-DD)
          example: YYYY-MM-D
        companiesHouseNumber:
          type: string
        parentFirmName:
          type: string
          minLength: 1
        parentFirmNumber:
          type: string
        solicitorAdvocate:
          type: boolean
          default: false
        advocateLevel:
          type: string
        barCouncilRollNumber:
          type: string
        highRisk:
          type: boolean
          default: false
        highRiskSupplier:
          type: boolean
          default: false
        firmIntervened:
          type: boolean
          default: false
        firmIntervenedDate:
          type: string
          format: date
          description: Date in ISO 8601 format (YYYY-MM-DD)
          example: YYYY-MM-D
        notForProfit:
          type: boolean
          default: false
      required:
        - providerName
